# Default values for pidor_app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: cr.yandex/crpr9jlf6k4254l80050/pidor_bot
  version: 937dc232d194a33affad4212ca0202268ea4f4c0
